name: "ArchLinux (makepkg)"
description: "ArchLinux (makepkg)"
author: shyaminayesh
branding:
  color: blue
  icon: box
runs:
  using: "docker"
  image: "docker://ghcr.io/enkodin/makepkg:latest"
inputs:
  command:
    description: "makepkg command to execute"
    required: true
    default: "--printsrc"
  files:
    description: "PKGBUILDs got changed or added"
    required: true
