name: "ArchLinux (makepkg)"
description: "ArchLinux (makepkg)"
author: shyaminayesh
branding:
  color: blue
  icon: box
runs:
  using: "docker"
  image: "docker://ghcr.io/enkodin/makepkg:latest"
inputs:
  src:
    description: "generate makepkg printsrc or not"
    required: true
    default: true
  publish:
    description: "publish package to aur"
    required: true
    default: false
  files:
    description: "PKGBUILDs got changed or added"
    required: true
