#!/usr/bin/env sh

echo ${INPUT_FILES} | jq --raw-output '.[]' | while read pkg; do

    ls -all /opt
    cd /opt
    pwd
    echo ${INPUT_SRC}

    # chown -R user:user ${pkg:0:-9}
    # cd ${pkg:0:-9}

    # runuser -u user -- makepkg ${INPUT_COMMAND}
    # echo ${pkg}
done
